### ISSUE TITLE
¿Cuáles son las Peticiones más comunes en el Protocolo HTTP?, ¿Para qué se usan? Ejemplifique.

### ISSUE THREAD

**Issue by guelo2019** [ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea3-grupo-7#1]

**Comment by recursosssbb** [comment]
[Punto_1_SilvanaBarea.pdf](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea3-grupo-7/files/11354737/Punto_1_SilvanaBarea.pdf)

**Comment by recursosssbb** [comment]
Estimado adjunto punto 1 tarea 3 grupo 7

[Punto_1_SilvanaBarea.pdf](https://github.com/ISPC-TST-ARQUITECTURA-Y-CONECTIVIDAD/tarea3-grupo-7/files/11354789/Punto_1_SilvanaBarea.pdf)
